<?php
$router->define([	
	''=>'Controllers/common/home.php',
	'index.php'=>'Controllers/common/home.php',
	'index'=>'Controllers/common/home.php',
	'reset_password'=>'Views/users/passwordResetForm.php',
	'splashmsg'=>'Views/common/splashmsg.php',
	'change_password'=>'Controllers/auth/updatePassword.php',
	'send_reset_password_link'=>'Controllers/auth/sendResetPasswordLink.php',
	'logout'=>'Controllers/auth/logout.php',
	'passwordreset'=>'Controllers/auth/resetPassword.php',
	'login'=>'Controllers/auth/login.php',
	'registration'=>'Controllers/auth/registration.php',
	'verify'=>'Controllers/auth/verifyRegistration.php',
	'gmail'=>'Controllers/auth/GmailRegistration.php',
	'addcat'=>'Controllers/bookCategories/AddCategory.php',
	'editcat'=>'Controllers/bookCategories/EditCategory.php',
	'delcat'=>'Controllers/bookCategories/DeleteCategory.php',
	'delusr'=>'Controllers/users/DeleteUser.php',
	'editbook'=>'Controllers/books/EditBook.php',
	'delbook'=>'Controllers/books/DeleteBook.php',
	'addbook'=>'Controllers/books/AddBook.php',
	'readbook'=>'Controllers/books/ReadBook.php',
	'filterBook'=>'Controllers/books/CategoryBooks.php',
	'sendreport'=>'Controllers/users/SendReport.php',
	'nudgeInactiveUser'=>'Controllers/AutomatedLogics/nudgingInactiveReaders.php'
]);
?>
